apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: green-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
